api:
  insecure: true
  dashboard: true

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: vku.sec.lab@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
